#!/usr/bin/env bash

cabal update

mkdir -p deps

_project="$(echo *.cabal | cut -d '.' -f 1)"

pushd deps > /dev/null

cp ../$_project.cabal ./

projects() {
  cabal install $_project --dry-run | grep hw- | grep -v "^${_project}-[0-9]\\+\\.[0-9]\\+\\.[0-9]\\+\\.[0-9]\\+$"
}

for x in $(projects); do
  stack unpack $x
done

rm ./$_project.cabal

popd > /dev/null
